MODEL:
  NUM_CLASSES: 2
INPUT:
  IMAGE_SIZE: 1024
DATASETS:
  TRAIN: ("voc_2007_trainval", "voc_2012_trainval")
  TEST: ("voc_2007_test", )
SOLVER:
  MAX_ITER: 35000
  LR_STEPS: [20000, 30000]
  GAMMA: 0.1
  BATCH_SIZE: 4
  LR: 1e-3

